spring:
 datasource:
  url: jdbc:mysql://localhost:3306/hello_test?useUnicode=true
  username: root
  password: 123456
  driverClassName: com.mysql.jdbc.Driver

server:
 port:80

logging:
 config:log4j2.xml