#!/usr/bin/python
# -*- coding:UTF-8 -*-
class Employee:
    '所有员工的基类'
    empCount = 0

    def __init__(self ,name, salary):
        self.name = name;
        self.salary = salary;
        Employee.empCount +=1;

    def dispalyCount(self):
        print("Total Employee Count %d" % Employee.empCount);

    def displayEmployee(self):
        print("Name: %s, Salary: %s" % (self.name, self.salary))

emp1 = Employee("zara", 3000);

emp1.displayEmployee();
emp1.dispalyCount();

print("Employee.__doc__:", Employee.__doc__);
print("Employee.__name__:", Employee.__name__);
print("Employee.__module__:", Employee.__module__);
print("Employee.__bases__:", Employee.__bases__);
print("Employee.__dict__:", Employee.__dict__);